apiVersion: apps/v1
kind: Deployment
metadata:
  name: jannat-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: jannat-app
        image: jannat7/django:1.1
        
        ports:
        - containerPort: 8000